name: Create Release

on:
  push:
    branches:
      - master

permissions: write-all

jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        # Pull the code from the repository.
        - name: Pull the code from the repository
          uses: actions/checkout@v3
        # Set up JDK 17 for the build (maven included).
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        # Build the project with Maven.
        - name: Compilation with Maven
          run: mvn compile
        # Get the project version from pom.xml.
        - name: Get Project Version from pom.xml
          id: pomVersion
          uses: entimaniac/read-pom-version-action@1.0.0
        # Create a release.
        - name: Create Release
          uses: actions/create-release@v1.1.4
          env:
            # This token is provided by Actions, you do not need to create your own token.
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: v${{ steps.pomVersion.outputs.version }}
            release_name: Version ${{ steps.pomVersion.outputs.version }}
            body_path: CHANGELOG.md
            draft: false
            prerelease: false
        # Deploy the artifacts to GitHub Package Registry.
        - name: Deploy to GitHub Package Registry
          uses: elgohr/Github-Action-Maven-Deploy@v1.0.0
          with:
            server: https://maven.pkg.github.com/botlify-net/bright-data-api
            repository: botlify-net/bright-data-api
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
