name: Create Release

on:
  push:
    branches:
      - master

jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        # Pull the code from the repository.
        - name: Pull the code from the repository
          uses: actions/checkout@v3
        # Set up JDK 17 for the build (maven included).
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        # Build the project with Maven.
        - name: Compilation with Maven
          run: mvn compile
        # Get the project version from pom.xml.
        - name: Get Project Version from pom.xml
          id: pomVersion
          uses: entimaniac/read-pom-version-action@1.0.0
        # Create a release.
        - name: Create Release
          uses: actions/create-release@v1.1.4
          env:
            # This token is provided by Actions, you do not need to create your own token.
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.pomVersion.outputs.version }}
            body_path: CHANGELOG.md
            release_name: Release ${{ steps.pom-version.outputs.version }}
            draft: false
            prerelease: false
